/**
 * Seeded activity and comments.
 *
 * Every entry carries an actor and a timestamp, and a change carries what
 * changed and what it went from and to -- the what/who/when the auditability
 * requirement asks for (brief s8f).
 *
 * Scope note worth keeping straight: comments are in Release 1, pulled in by
 * the review-and-approval feature. The *browsable* activity history is
 * backlog -- Release 1 requires the record to exist, not to be readable in a
 * UI. Both are drawn here because the wireframes are where the team decides
 * what that surface should look like when it does arrive.
 */

import { PEOPLE } from "./fixtures";
import type { ActivityEntry } from "./types";

export const ACTIVITY: readonly ActivityEntry[] = [
  // --- e-04 Hybrid Leadership Summit ---------------------------------------
  {
    id: "a-01",
    eventId: "e-04",
    section: "overview",
    kind: "activity",
    actor: PEOPLE.organiserPriya,
    at: "2026-09-02 09:12",
    action: "submitted the request",
  },
  {
    id: "a-02",
    eventId: "e-04",
    section: "overview",
    kind: "activity",
    actor: PEOPLE.opsManagerDaniel,
    at: "2026-09-02 11:05",
    action: "assigned a coordinator",
    field: "Coordinator",
    from: "Unassigned",
    to: "Nadia",
  },
  {
    id: "a-03",
    eventId: "e-04",
    section: "overview",
    kind: "activity",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-03 10:40",
    action: "started the review",
    field: "Request status",
    from: "Submitted",
    to: "Under Review",
  },
  {
    id: "a-04",
    eventId: "e-04",
    section: "overview",
    kind: "comment",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-06 14:22",
    body: "Alice, can you confirm whether the streamed sessions need live interpretation as well as captions? It changes what I ask technical support for.",
    parentId: null,
  },
  {
    id: "a-05",
    eventId: "e-04",
    section: "overview",
    kind: "comment",
    actor: PEOPLE.organiserPriya,
    at: "2026-09-07 08:15",
    body: "Captions only. Interpretation is not needed this year.",
    parentId: "a-04",
  },
  {
    id: "a-06",
    eventId: "e-04",
    section: "venue",
    kind: "activity",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-07 10:20",
    action: "requested Hall A for 18 November, AM + PM",
  },
  {
    id: "a-07",
    eventId: "e-04",
    section: "venue",
    kind: "comment",
    actor: PEOPLE.venueMei,
    at: "2026-09-07 12:02",
    body: "Holding off until I know whether the stage lift is needed — the summit's accessibility note mentions captions but not mobility.",
    parentId: null,
  },
  {
    id: "a-08",
    eventId: "e-04",
    section: "technical",
    kind: "activity",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-05 16:12",
    action: "recorded the equipment requirements",
  },
  {
    id: "a-09",
    eventId: "e-04",
    section: "technical",
    kind: "activity",
    actor: PEOPLE.technicalRavi,
    at: "2026-09-07 15:30",
    action: "reviewed the reservation",
    field: "Reservation status",
    from: "Requested",
    to: "Partially Reserved",
  },
  {
    id: "a-10",
    eventId: "e-04",
    section: "technical",
    kind: "comment",
    actor: PEOPLE.technicalRavi,
    at: "2026-09-07 15:34",
    body: "Both lighting rigs are out for inspection until 22 November. I can source a hire rig if the budget allows — say the word and I will price it.",
    parentId: null,
  },
  {
    id: "a-11",
    eventId: "e-04",
    section: "technical",
    kind: "comment",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-08 09:03",
    body: "Please price it. The keynote is the only session that really needs it.",
    parentId: "a-10",
  },
  {
    id: "a-12",
    eventId: "e-04",
    section: "readiness",
    kind: "activity",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-06 17:45",
    action: "marked the programme complete",
    field: "Programme agreed",
    from: "Outstanding",
    to: "Done",
  },

  // --- e-05 Graduate Recruitment Open Day ----------------------------------
  {
    id: "a-13",
    eventId: "e-05",
    section: "overview",
    kind: "activity",
    actor: PEOPLE.coordinatorJonas,
    at: "2026-09-04 09:10",
    action: "approved the request",
    field: "Request status",
    from: "Under Review",
    to: "Approved",
  },
  {
    id: "a-14",
    eventId: "e-05",
    section: "venue",
    kind: "activity",
    actor: PEOPLE.coordinatorJonas,
    at: "2026-09-03 14:20",
    action: "requested Hall A for 2 October, PM",
  },
  {
    id: "a-15",
    eventId: "e-05",
    section: "venue",
    kind: "activity",
    actor: PEOPLE.venueMei,
    at: "2026-09-04 09:47",
    action: "rejected the booking",
    field: "Booking status",
    from: "Requested",
    to: "Rejected",
  },
  {
    id: "a-16",
    eventId: "e-05",
    section: "venue",
    kind: "comment",
    actor: PEOPLE.venueMei,
    at: "2026-09-04 09:48",
    body: "Hall A is committed to a contracted client that whole day, and the loading bay is closed for resurfacing that week. Innovation Suite would take the booths at a squeeze.",
    parentId: null,
  },
  {
    id: "a-17",
    eventId: "e-05",
    section: "venue",
    kind: "comment",
    actor: PEOPLE.coordinatorJonas,
    at: "2026-09-04 11:15",
    body: "Innovation Suite holds 120 and we are expecting 250. Checking whether the client will split across two sessions.",
    parentId: "a-16",
  },

  // --- e-06 Autumn Product Showcase ----------------------------------------
  {
    id: "a-18",
    eventId: "e-06",
    section: "venue",
    kind: "activity",
    actor: PEOPLE.venueMei,
    at: "2026-09-01 10:05",
    action: "approved the booking",
    field: "Booking status",
    from: "Requested",
    to: "Confirmed",
  },
  {
    id: "a-19",
    eventId: "e-06",
    section: "technical",
    kind: "activity",
    actor: PEOPLE.technicalRavi,
    at: "2026-09-01 11:30",
    action: "reserved all equipment lines",
    field: "Reservation status",
    from: "Requested",
    to: "Reserved",
  },
  {
    id: "a-20",
    eventId: "e-06",
    section: "readiness",
    kind: "activity",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-01 16:40",
    action: "confirmed the event",
    field: "Event status",
    from: "Planning",
    to: "Confirmed",
  },
  {
    id: "a-21",
    eventId: "e-06",
    section: "registration",
    kind: "activity",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-01 16:42",
    action: "opened registration",
    field: "Registration window",
    from: "Not set",
    to: "1 Sep – 10 Oct, capped at 120",
  },
  {
    id: "a-22",
    eventId: "e-06",
    section: "registration",
    kind: "comment",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-09-05 08:20",
    body: "Grace Lim withdrew, so we are back to three live places taken. No waiting list this release, so the place simply frees up.",
    parentId: null,
  },

  // --- e-07 Compliance Training Workshop -----------------------------------
  {
    id: "a-23",
    eventId: "e-07",
    section: "overview",
    kind: "activity",
    actor: PEOPLE.coordinatorJonas,
    at: "2026-09-06 10:02",
    action: "approved the request",
    field: "Request status",
    from: "Under Review",
    to: "Approved",
  },
  {
    id: "a-24",
    eventId: "e-07",
    section: "venue",
    kind: "activity",
    actor: PEOPLE.coordinatorJonas,
    at: "2026-09-08 13:55",
    action: "requested Seminar Room 3 for 3 December, AM",
  },
  {
    id: "a-25",
    eventId: "e-07",
    section: "technical",
    kind: "activity",
    actor: PEOPLE.coordinatorJonas,
    at: "2026-09-06 11:30",
    action: "recorded the equipment requirements",
  },

  // --- e-03 Annual Client Forum --------------------------------------------
  {
    id: "a-26",
    eventId: "e-03",
    section: "overview",
    kind: "activity",
    actor: PEOPLE.organiserPriya,
    at: "2026-09-08 09:14",
    action: "submitted the request",
  },

  // --- e-08 Summer Networking Evening --------------------------------------
  {
    id: "a-27",
    eventId: "e-08",
    section: "overview",
    kind: "activity",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-07-25 09:00",
    action: "marked the event completed",
    field: "Event status",
    from: "Confirmed",
    to: "Completed",
  },
  {
    id: "a-28",
    eventId: "e-08",
    section: "overview",
    kind: "comment",
    actor: PEOPLE.coordinatorAmara,
    at: "2026-07-25 09:04",
    body: "PA cut out briefly at 19:20; spare mic covered it. 64 of 72 registered attended. Nothing to chase.",
    parentId: null,
  },
];
